import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navigation from "./components/Navigation/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className + " h-screen overflow-hidden grid grid-cols-[350px_1fr] gap-8"}>
        <Navigation />
        <div className="overflow-scroll">{children}</div>
      </body>
    </html>
  );
}
